import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { Bagel_Fat_One } from "next/font/google";

const bagelFatOne = Bagel_Fat_One({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-bagel-fat-one",
});

const dunggeunmo = localFont({
  src: "./fonts/DungGeunMo.woff2",
  display: "swap",
  weight: "45 920",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${bagelFatOne.variable} ${dunggeunmo.className}`}>
        {children}
      </body>
    </html>
  );
}
